### ISSUE TITLE
Incorrect generation for list of nullable objects

### ISSUE THREAD

**Issue by Tetraquark** [icerockdev/moko-network#131]
I got schema like this:

```
    BlogPermissionsRoles:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
          nullable: true
```

And the generator makes the wrong type for this scheme:

```kotlin
kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.String>>
```

Should be nullable `kotlin.String` inside `List`.

**Comment by Tetraquark** [comment]
It looks like there are no ways to fix it inside moko-network-generator. So, the way to work around this problem is to declare a schema in the specification using `oneOf` operator: 

```
BlogPermissionsRoles:
  type: object
  additionalProperties:
    type: array
    items:
      oneOf:
        - type: null
        - type: string
```
