### ISSUE TITLE
Missing query param default value

### ISSUE THREAD

**Issue by belousovgm** [icerockdev/moko-network#174]
Hello! I faced a problem when was trying to use default parameter value:

parameter statement:
```
      parameters:
        - in: query
          name: parameter
          schema:
            type: string
            default: 'value'
```

expected generated code:
```
suspend fun get(parameter: kotlin.String? = "value") : Response
```

actual generated code:
```
suspend fun get(parameter: kotlin.String? = null) : Response
```
