### ISSUE TITLE
Invalid enum classes are generated by network-generator

### ISSUE THREAD

**Issue by Tetraquark** [icerockdev/moko-network#47]
For example for that scheme:

```yaml
    StatusType:
      type: string
      enum:
        - need-action
        - accepted
        - rejected
        - maybe
```

Generates enum class with errors:

```kotlin
@Serializable
enum class StatusType(override val serialName: String? = null): SerialEnum {

    @SerialName("need-action")
    NEED_MINUS_ACTION,

    @SerialName("accepted")
    ACCEPTED,

    @SerialName("rejected")
    REJECTED,

    @SerialName("maybe")
    MAYBE;

}
```

Need to remove `SerialEnum` and property overriding from templates.
