### ISSUE TITLE
Map "object" property without internal properties to JsonObject type

### ISSUE THREAD

**Issue by Alex009** [icerockdev/moko-network#67]
this:
```
UserNotification:
  type: object
  properties:
    id:
      title: ID
      type: integer
      readOnly: true
    content:
      type: object
```

should be:
```
@Serializable
public data class UserNotification (
    @SerialName("id")
    val id: kotlin.Int? = null,
    @SerialName("content")
    val content: JsonObject? = null
)
```
