### ISSUE TITLE
Api generation error for nullable enum types

### ISSUE THREAD

**Issue by kovalandrew** [icerockdev/moko-network#89]
If spec contains nullable enum type and one of items is null it will fail generation:
```
layout_name:
              title: Название шаблона отображения
              type: string
              enum:
                - null
                - layout_1
                - layout_2
                - layout_3
              nullable: true
```

For generation should remove `- null` item for success generation:

```
layout_name:
              title: Название шаблона отображения
              type: string
              enum:
                - layout_1
                - layout_2
                - layout_3
              nullable: true
```
